name: CI

on:
  push:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache local Maven repository
        id: cache-maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Download Spigot Buildtools
        if: steps.cache-maven.outputs.cache-hit != 'true'
        run: |
          mkdir ~/spigot-buildtools
          cd ~/spigot-buildtools
          wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar

      - name: Setup JDK 8
        uses: actions/setup-java@v4
        if: steps.cache-maven.outputs.cache-hit != 'true'
        with:
          java-version: 8
          distribution: temurin

      - name: Install Spigot 1.16.5
        if: steps.cache-maven.outputs.cache-hit != 'true'
        run: if [ ! -f "~/.m2/repository/org/spigotmc/spigot/1.16.5-R0.1-SNAPSHOT/spigot-1.16.5-R0.1-SNAPSHOT.jar" ]; then cd ~/spigot-buildtools && java -jar BuildTools.jar --rev 1.16.5; fi

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        if: steps.cache-maven.outputs.cache-hit != 'true'
        with:
          java-version: 17
          distribution: temurin

      - name: Install Spigot 1.17.1
        if: steps.cache-maven.outputs.cache-hit != 'true'
        run: if [ ! -f "~/.m2/repository/org/spigotmc/spigot/1.17.1-R0.1-SNAPSHOT/spigot-1.17.1-R0.1-SNAPSHOT.jar" ]; then cd ~/spigot-buildtools && java -jar BuildTools.jar --rev 1.17.1; fi

      - name: Install Spigot 1.18.2
        if: steps.cache-maven.outputs.cache-hit != 'true'
        run: if [ ! -f "~/.m2/repository/org/spigotmc/spigot/1.18.2-R0.1-SNAPSHOT/spigot-1.18.2-R0.1-SNAPSHOT.jar" ]; then cd ~/spigot-buildtools && java -jar BuildTools.jar --rev 1.18.2; fi

      - name: Install Spigot 1.19.4
        if: steps.cache-maven.outputs.cache-hit != 'true'
        run: if [ ! -f "~/.m2/repository/org/spigotmc/spigot/1.19.4-R0.1-SNAPSHOT/spigot-1.19.4-R0.1-SNAPSHOT.jar" ]; then cd ~/spigot-buildtools && java -jar BuildTools.jar --rev 1.19.4; fi

      - name: Setup JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: 22
          distribution: temurin

      - name: Install Spigot 1.20.4
        if: steps.cache-maven.outputs.cache-hit != 'true'
        run: if [ ! -f "~/.m2/repository/org/spigotmc/spigot/1.20.4-R0.1-SNAPSHOT/spigot-1.20.4-R0.1-SNAPSHOT-remapped-mojang.jar" ]; then cd ~/spigot-buildtools && java -jar BuildTools.jar --rev 1.20.4 --remapped; fi

      - name: Install Spigot 1.20.6
        if: steps.cache-maven.outputs.cache-hit != 'true'
        run: if [ ! -f "~/.m2/repository/org/spigotmc/spigot/1.20.6-R0.1-SNAPSHOT/spigot-1.20.6-R0.1-SNAPSHOT-remapped-mojang.jar" ]; then cd ~/spigot-buildtools && java -jar BuildTools.jar --rev 1.20.6 --remapped; fi

      - name: Install Spigot 1.21.1
        if: steps.cache-maven.outputs.cache-hit != 'true'
        run: if [ ! -f "~/.m2/repository/org/spigotmc/spigot/1.21.1-R0.1-SNAPSHOT/spigot-1.21.1-R0.1-SNAPSHOT-remapped-mojang.jar" ]; then cd ~/spigot-buildtools && java -jar BuildTools.jar --rev 1.21.1 --remapped; fi

      - name: Build with Maven
        run: |
          mvn --version
          mvn --batch-mode --no-transfer-progress clean package
          echo "version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: EzChestShop-${{ env.version }}+${{ github.run_number }}
          path: |
            target/EzChestShop-*.jar
            !target/original-EzChestShop-*.jar
