name: CI

on:
  push:
    branches-ignore:
      - dependabot/**
  pull_request:

jobs:
  build:
    name: Build with Gradle
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: gradle

      - name: Build with Gradle
        run: |
          ./gradlew clean build --no-daemon --console=plain
          echo "VERSION=$(./gradlew properties --no-daemon --console=plain -q | grep "^version:" | awk '{printf $2}')" >> $GITHUB_ENV

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: EzChestShopReborn-${{ env.VERSION }}
          path: |
            paper-plugin/build/libs/EzChestShopReborn-*.jar

      - name: Publish to Discord
        if: github.repository == 'nouish/EzChestShop' && github.ref == 'refs/heads/main' && contains(env.VERSION, '-SNAPSHOT')
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -X POST \
          -F "payload_json={\"content\": \"**Build Artifact:** ${{ env.VERSION }}\"}" \
          -F "file=@paper-plugin/build/libs/EzChestShopReborn-${{ env.VERSION }}.jar" \
          "$DISCORD_WEBHOOK_URL"
